<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AudiosurfInterface\AudiosurfInterface.csproj" />
    <ProjectReference Include="..\TweakerCore\TweakerCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="QuickPlayerCore.Tests" />
  </ItemGroup>

</Project>
