<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Core\" />
	  <Folder Include="Settings\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Tweaker.Core\Tweaker.Core.csproj" />
	</ItemGroup>

</Project>
