#pragma once

/**
 * @file config.h
 * @brief Configuration header for mmap library
 *
 * This file is auto-generated by CMake. Do not edit manually.
 */

// Architecture configuration
#define MMAP_MACHINE_32 1
/* #undef MMAP_MACHINE_64 */

// Architecture macros for code usage
#if 1
    #define MACHINE_32 1
    #define MACHINE_64 0
#elif 0
    #define MACHINE_32 0
    #define MACHINE_64 1
#else
    #error "Architecture not defined. Please set MMAP_ARCHITECTURE to x32 or x64"
#endif

// Project version
#define MMAP_VERSION_MAJOR 1
#define MMAP_VERSION_MINOR 0
#define MMAP_VERSION_PATCH 0

// Helper macros
#if MACHINE_32
    #define ARCH_NAME "x32"
    #define POINTER_SIZE 4
#else
    #define ARCH_NAME "x64"
    #define POINTER_SIZE 8
#endif
